export default [
  "Princeton University",
  "Harvard University",
  "Columbia University",
  "MIT",
  "Yale University",
  "Stanford University",
  "University of Chicago",
  "University of Pennsylvania",
  "California Institute of Technology",
  "Johns Hopkins University",
  "Northwestern University",
  "Dartmouth College",
  "Brown University",
  "Vanderbilt University",
  "Rice University",
  "Washington University in St. Louis",
  "Cornell University",
  "University of Notre Dame",
  "UCLA",
  "Emory University",
  "UC Berkeley",
  "Georgetown University",
  "University of Michigan -- Ann Arbor",
  "University of Southern California",
  "Carnegie Mellon University",
  "University of Virginia",
  "University of North Carolina -- Chapel Hill",
  "Wake Forest University",
  "New York University",
  "Tufts University",
  "UCSB",
  "University of Florida",
  "University of Rochester",
  "Boston College",
  "Georgia Institute of Technology",
  "UCI",
  "UCSD",
  "UCD",
  "William & Mary",
  "Tulane",
  "Boston University",
  "Brandeis University",
  "Case Western Reserve University",
  "University of Texas at Austin",
  "University of Wisconsin -- Madison",
  "University of Georgia",
  "UIUC",
  "Lehigh University",
  "Northeastern University",
  "Pepperdine University"
]
